# Generated by Django 4.2 on 2024-02-19 20:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subdivisions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WomenConsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timely_medication_provision', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Своевременное обеспечение беременных лекарственными препаратами за счет средств родовых сертификатов (витаминами)')),
                ('doctor_availability', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Доступность врачей акушеров-гинекологов')),
                ('complaints', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Жалобы (своевременный ответ в днях)')),
                ('timely_screening_referral', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Своевременное направление на пренатальный скрининг(первый и второй)')),
                ('timely_childbirth_referral', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Своевременное направление на роды в зависимостиот установленной степени риска')),
                ('reducing_requests_number', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Снижение количества обращений')),
                ('schedule_for_weeks', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Формирование расписания врачей на 3 недели вперед')),
                ('doctor_digital_signatures', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Электронные цифровые подписи врачей')),
                ('telemed_consultations_protocol', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Протокол Телемедицинских консультаций Врач-Пациент) в женской консультации')),
                ('templates_using', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Использование шаблонов по акушерству и гинекологии')),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('subdivision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subdivisions.womenconssubdivision', verbose_name='reports')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
            },
        ),
        migrations.CreateModel(
            name='StomatologyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_feedback', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Обратная связь пациента')),
                ('complaints', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Жалобы (своевременный ответ в днях)')),
                ('patient_non_attendance', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Неявки на прием врача')),
                ('doctor_availability', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Доступность врачей стоматологов (стоматологи терапевтические, стоматологи детские)')),
                ('cancer_screening_plan', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Мониторинг исполнения плана по онкоскринингу')),
                ('reducing_requests_number', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Снижение количества обращений')),
                ('schedule_for_weeks', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Формирование расписания врачей на 3 недели вперед')),
                ('insurance_plan', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Выполнение объемов обязательного медицинского страхования')),
                ('templates_using', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Мониторинг использования шаблонов по стоматологии')),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('subdivision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subdivisions.stomatologysubdivision', verbose_name='reports')),
            ],
        ),
        migrations.CreateModel(
            name='OncologyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('subdivision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subdivisions.oncologysubdivision', verbose_name='reports')),
            ],
        ),
        migrations.CreateModel(
            name='HosiltalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('subdivision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subdivisions.hospitalsubdivision', verbose_name='reports')),
            ],
        ),
        migrations.CreateModel(
            name='ChildReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('subdivision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subdivisions.childsubdivision', verbose_name='reports')),
            ],
        ),
        migrations.CreateModel(
            name='APPReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('subdivision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subdivisions.appsubdivision', verbose_name='reports')),
            ],
        ),
    ]
