# Generated by Django 4.2 on 2024-02-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APPSubdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Наименование подразделения')),
            ],
            options={
                'verbose_name': 'Амбулаторно-поликлиническое подразделение',
                'verbose_name_plural': 'Амбулаторно-поликлинические подразделения',
            },
        ),
        migrations.CreateModel(
            name='ChildSubdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Наименование подразделения')),
            ],
            options={
                'verbose_name': 'Детская поликлиника',
                'verbose_name_plural': 'Детские поликлиники',
            },
        ),
        migrations.CreateModel(
            name='HospitalSubdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Наименование подразделения')),
            ],
            options={
                'verbose_name': 'подразделение Стационара',
                'verbose_name_plural': 'подразделения Стационара',
            },
        ),
        migrations.CreateModel(
            name='OncologySubdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Наименование подразделения')),
            ],
            options={
                'verbose_name': 'Онкологическое подразделение',
                'verbose_name_plural': 'Онкологические подразделения',
            },
        ),
        migrations.CreateModel(
            name='StomatologySubdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Наименование подразделения')),
            ],
            options={
                'verbose_name': 'Стоматологическое подразделение',
                'verbose_name_plural': 'Стоматологические подразделения',
            },
        ),
        migrations.CreateModel(
            name='WomenConsSubdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Наименование подразделения')),
            ],
            options={
                'verbose_name': 'Женская консультация',
                'verbose_name_plural': 'Женские консультации',
            },
        ),
    ]
